export const skillsData = {
  id: "skills",
  title: "Skills",
  description: "",
  skill_list: [
    "React",
    "Redux",
    "Recoil",
    "Context API",
    "Styled Components",
    "JavaScript",
    "TypeScript",
    "HTML",
    "CSS",
    "LESS/SASS",
    "Node/Express",
    "Knex",
    "SQLite3",
    "PostgreSQL",
    "Git",
    "CI/CD",
    "AWS Amplify",
    "React Testing Library",
    "Jest",
    "Cypress.io",
    "Python",
    "Agile Workflow",
    "Deployment",
  ],
};
